version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4.9-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-cache-v1-{{ checksum "./composer.lock" }}
            - composer-cache-v1
      - run:
          name: "Install composer dependencies"
          command: composer install --no-interaction
      - save_cache:
          key: composer-cache-v1-{{ checksum "./composer.lock" }}
          paths:
            - ./vendor
      - run:
          name: "Display composer version"
          command: "composer --version"
      - run:
          name: "Run tests"
          command: "composer run test:coverage"
      - run:
          name: "Send coverage"
          command: "bash <(curl -s https://codecov.io/bash) -t c9aad3ac-0438-4d28-9ee4-255cb6683823"
